import React from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { useDispatch } from 'react-redux';
//import { setBillData } from './billSlice';
import { setBillData } from '../store/billSlice';


export default function Bill() {
  const location = useLocation();
  const {
    Sender_name, price, quantity, sender_add, sender_pinc, sender_mobile, sender_email,
    sender_city, sender_item, bookingdate, bookingtime, reciever_name, reciever_add,
    reciever_pinc, reciever_mobile, reciever_email, reciever_city,
  } = location.state;

  const navigate = useNavigate();
  const dispatch = useDispatch();

  function gotoadmin(e) {
    e.preventDefault();

    // Dispatch data to Redux store
    dispatch(
      setBillData({
        senderDetails: {
          name: Sender_name,
          address: sender_add,
          pincode: sender_pinc,
          mobile: sender_mobile,
          email: sender_email,
          city: sender_city,
          item: sender_item,
        },
        receiverDetails: {
          name: reciever_name,
          address: reciever_add,
          pincode: reciever_pinc,
          mobile: reciever_mobile,
          email: reciever_email,
          city: reciever_city,
        },
        bookingDetails: {
          date: bookingdate,
          time: bookingtime,
          price: price,
          quantity: quantity,
        },
      })
    );


  }

  return (
    <div className="row billbackground">
      <div className="rowww">
        <h1 id="text">Your pickup request is created successfully</h1>
        <div className="billbox">
          <div className="bill">
            <p className="billdata">Your bill is generated by name: {Sender_name}</p>
            <p className="billdata">Quantity is: {quantity}</p>
            <p className="billdata">Total amount is: ₹{price}</p>
            <button id="paybutton" type="submit" onClick={gotoadmin}>Pay Bill</button>
          </div>
        </div>
      </div>
    </div>
  );
}
